### ISSUE TITLE
[Question] Does this mod work with RoadRunner?

### ISSUE THREAD

**Issue by Kasualix** [CorgiTaco-Archive/No-Client-Side-Entity-Collision-Checks#8]
Minecraft 1.16.5 Forge 36.2.39
RoadRunner-mc1.16.5-1.4.1.jar
entitycollisionfpsfix-1.16-1.0.1.jar

I saw that RoadRunner has mixin about entity collision [here](https://github.com/MaxNeedsSnacks/roadrunner/tree/1.16.x/forge/src/main/java/me/jellysquid/mods/lithium/mixin/entity/collisions)

**Comment by FearAK** [comment]
Did you ever find out since you closed it? If so, care to share?

**Comment by Kasualix** [comment]
I've stopped using RoadRunner as it's not optimization at all for me.

**Comment by Kasualix** [comment]
Lithium forge port is just very unstable and buggy, as for me.
